const { chromium } = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const path = require('node:path');
const legacy = {books:[{t:'독서의 기술',s:'8/1',e:[{l:'나 자신이 배제된 해결책은 효과가 없다.',d:'8/2'}]},{t:'어떻게 살아낼 것인가',s:'8/3',e:[]}],thoughts:[{t:'잊기 전에 남긴 생각',d:'8/4'}],trips:[{p:'통영',n:'바다를 오래 보았다.'}],cur:0};
(async()=>{
 const browser=await chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL || 'msedge'});
 const context=await browser.newContext({viewport:{width:1280,height:900},acceptDownloads:true});
 const page=await context.newPage(); const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await context.addInitScript(data=>{if(!localStorage.getItem('test-seeded')){localStorage.setItem('onemonth_v1',JSON.stringify(data));localStorage.setItem('test-seeded','1');}},legacy);
 await page.goto('http://127.0.0.1:4173');
 await page.getByRole('heading',{name:'나의 책장'}).waitFor();
 assert.equal(await page.locator('.book-tile').count(),2);
 assert.deepEqual(await page.evaluate(()=>JSON.parse(localStorage.getItem('onemonth_v1'))),legacy);
 console.log('PASS migration: books, original localStorage intact');
 await page.locator('.book-tile').first().click();
 await page.getByRole('button',{name:'＋ 문장 남기기'}).click();
 await page.getByLabel('오래 두고 싶은 문장').fill('새 문장 <script>alert(1)</script>');
 await page.getByLabel('페이지 · 선택').fill('42');
 await page.getByLabel('내 생각 · 선택').fill('도서관에서 든 생각');
 await page.getByRole('button',{name:'기록 저장',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 assert.equal(await page.locator('.record').count(),2);
 assert.match(await page.locator('.record').first().innerText(),/도서관/);
 await page.locator('.record').first().getByRole('button',{name:'수정',exact:true}).click();
 await page.getByLabel('오래 두고 싶은 문장').fill('수정한 문장');
 await page.getByRole('button',{name:'닫기',exact:true}).last().click();
 await page.locator('.record').first().getByRole('button',{name:'수정',exact:true}).click();
 assert.equal(await page.getByLabel('오래 두고 싶은 문장').inputValue(),'수정한 문장');
 await page.getByRole('button',{name:'기록 저장',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.locator('.record').first().getByRole('button',{name:'삭제',exact:true}).click();
 await page.getByRole('button',{name:'되돌리기',exact:true}).click();
 await page.getByText('기록을 되돌렸습니다.',{exact:true}).waitFor();
 assert.equal(await page.locator('.record').count(),2);
 console.log('PASS add/edit/draft/delete/undo and escaped text');
 await page.locator('[data-entry-tab="questions"]').click();
 await page.getByRole('button',{name:'＋ 질문 남기기'}).click();
 await page.getByLabel('읽다가 생긴 물음').fill('책이 나에게 남기는 것은?');
 await page.getByRole('button',{name:'기록 저장',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.getByRole('button',{name:'답 남기기',exact:true}).click();
 await page.getByLabel('지금 떠오른 답').fill('생각할 여유');
 await page.getByRole('button',{name:'기록 저장',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 assert.equal(await page.locator('.answer').innerText(),'생각할 여유');
 await page.getByRole('link',{name:'남은 질문',exact:true}).click();
 await page.getByRole('button',{name:'답을 남긴',exact:true}).click();
 assert.equal(await page.locator('.record').count(),1);
 console.log('PASS question/answer cross-book view');
 await page.getByRole('link',{name:'책장',exact:true}).click();
 await page.getByLabel('책과 기록 검색').fill('도서관');
 assert.equal(await page.locator('.book-tile').count(),1);
 await page.getByLabel('책과 기록 검색').fill('');
 await page.getByRole('button',{name:'＋ 책 추가',exact:true}).click();
 await page.getByLabel('책 제목',{exact:true}).fill('사진 표지를 가진 책');
 const png=Buffer.from(await page.evaluate(()=>{const c=document.createElement('canvas');c.width=200;c.height=300;const x=c.getContext('2d');x.fillStyle='#d7cab2';x.fillRect(0,0,200,300);return c.toDataURL('image/png').split(',')[1];}),'base64');
 await page.locator('#cover-file').setInputFiles({name:'cover.png',mimeType:'image/png',buffer:png});
 await page.waitForFunction(()=>document.querySelector('#cover-preview img')?.src.startsWith('data:image/jpeg'));
 await page.getByRole('button',{name:'책장에 넣기',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.getByRole('heading',{name:'사진 표지를 가진 책',exact:true}).waitFor();
 await page.reload();
 await page.getByRole('heading',{name:'사진 표지를 가진 책',exact:true}).waitFor();
 assert.match(await page.locator('.book-hero img').getAttribute('src'),/^data:image\/jpeg/);
 console.log('PASS uploaded photo persists through reload');
 await page.getByRole('button',{name:'백업과 보관 설정'}).click();
 const downloadPromise=page.waitForEvent('download');
 await page.getByRole('button',{name:'전체 기록 내보내기',exact:true}).click();
 const download=await downloadPromise; const exported=JSON.parse(await fs.readFile(await download.path(),'utf8'));
 assert.equal(exported.data.books.length,3); assert.match(exported.data.books[2].cover,/^data:image/);
 await page.locator('#import').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from('{"books":[{"t":"bad","e":{}}]}')});
 await page.getByText(/복원하지 않았습니다/).waitFor();
 assert.equal(await page.locator('#confirm-restore').count(),0);
 await page.locator('#import').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});
 await page.getByRole('button',{name:'현재 기록 백업 후 교체'}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.getByRole('heading',{name:'나의 책장'}).waitFor();
 assert.equal(await page.locator('.book-tile').count(),2);
 console.log('PASS backup photo inclusion, malformed rejection, full legacy restore');
 await page.getByRole('button',{name:'백업과 보관 설정'}).click();
 await page.getByRole('button',{name:'직전 상태 확인'}).click();
 await page.getByRole('button',{name:'현재 기록 백업 후 교체'}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 assert.equal(await page.locator('.book-tile').count(),3);
 console.log('PASS previous-snapshot recovery');
 await fs.mkdir('tests/artifacts',{recursive:true});
 await page.screenshot({path:'tests/artifacts/desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'tests/artifacts/mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 await page.locator('.book-tile').first().click();
 await page.screenshot({path:'tests/artifacts/book-mobile.png',fullPage:true});
 await page.getByRole('button',{name:'책 정보 수정',exact:true}).click();
 await page.screenshot({path:'tests/artifacts/editor-mobile.png',fullPage:true});
 assert.ok(await page.evaluate(()=>document.querySelector('dialog').scrollWidth<=document.querySelector('dialog').clientWidth));
 await page.getByRole('button',{name:'닫기',exact:true}).first().click();
 await page.evaluate(async()=>{await navigator.serviceWorker.ready;});
 await page.reload(); await page.getByRole('heading',{name:'독서의 기술',exact:true}).waitFor();
 assert.ok(await page.evaluate(()=>!!navigator.serviceWorker.controller));
 await context.setOffline(true); await page.reload();
 await page.getByRole('heading',{name:'독서의 기술',exact:true}).waitFor();
 await page.locator('[data-entry-tab="entries"]').click();
 await page.getByRole('button',{name:'＋ 문장 남기기'}).click();
 await page.getByLabel('오래 두고 싶은 문장').fill('오프라인에서도 남기는 문장');
 await page.getByRole('button',{name:'기록 저장',exact:true}).click();
 await page.locator('#editor').waitFor({state:'hidden'});
 await page.getByText('오프라인에서도 남기는 문장',{exact:true}).waitFor();
 console.log('PASS mobile layouts and offline reload/write');
 assert.deepEqual(errors,[]); console.log('PASS no page errors');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
